package expression.parser;

public enum LexemeType {
    LEFT_ROUND, LEFT_SQUARE, LEFT_CURLY, RIGHT_ROUND, RIGHT_SQUARE, RIGHT_CURLY,
    ADD, SUBTRACT, UNARY, MULTIPLY, DIVIDE, CONST, VARIABLE, END, AND, XOR, OR, LOnes, TOnes, MIN, MAX
}